openapi: 3.0.1
info:
  version: 1.0.0
  title: Hacker News (ProjecteG14B)
  description: "This is the Open API documentation for the REST API of our beloved application **Hacker News** deployed at <https://hackernews-projecteg14b.herokuapp.com/>. <br>All operations are executable. Some operations require authentication. In this case, you must **Authorize** your request by providing the api_key vaule you got when you created your user in the HackerNews Web App."
servers:
  - url: 'https://hackernews-projecteg14b.herokuapp.com/'
  - url: 'http://ip-p√∫blica-AWSCloud9:8080'
paths:
  /contributions:
    get:
      tags:
      - contributions
      summary: Retrieves all the Contributions of type url (ordered by points), of type ask (ordered by points), of type all (ordered by creation), created by one User or voted by the logged in User
      operationId: getContributions
      parameters:
      - name: type
        in: query
        description: Contribution type to filter
        required: false
        schema:
          type: string
          enum: [all, url, ask]
      - name: user_id
        in: query
        description: Contribution user to filter
        schema:
          type: integer
      - name: upvotedS
        in: query
        description: upvoted contributions of logged in User
        schema:
          type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contribution'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorUserExample:
                  $ref: '#/components/examples/error404User'
        401:
          description: 'Error: Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorMissingAuthenticationExample:
                  $ref: '#/components/examples/error401UnauthorizedMissingAuthentication'
                errorIncorrectAuthenticationExample:
                  $ref: '#/components/examples/error401UnauthorizedIncorrectAuthentication'
        403:
          description: 'Error: Forbidden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorPrivilegeNotGrantedExample:
                  $ref: '#/components/examples/error403Forbidden'
    post:
      tags:
      - contributions
      summary: Adds a new Contribution to the HackerNews
      operationId: addContribution
      requestBody:
        description: Provide the title, the url (optional) & text (optional) of the new Contribution
        content:
          application/json:
            schema:
              required:
              - title
              - url
              - text
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                  example: 'Contribution title'
                url:
                  type: string
                  format: url
                  nullable: true
                  example: 'https://www.contribution-url.com'
                text:
                  type: string
                  nullable: true
                  example: 'Contribution text'
        required: true
      responses:
        201:
          description: Contribution created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contribution'
        400:
          description: 'Error: Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorTitleEmptyExample:
                  $ref: '#/components/examples/error400TitleContribution'
                errorURLInvalidExample:
                  $ref: '#/components/examples/error400URLContribution'
        401:
            description: 'Error: Unauthorized'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorMissingAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedMissingAuthentication'
                  errorIncorrectAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedIncorrectAuthentication'
        409:
            description: 'Error: Conflict'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorURLExistenceExample:
                    $ref: '#/components/examples/error409Contribution'
  /contributions/{contributionId}:
    get:
      tags:
      - contributions
      summary: Finds a Contribution by its ID
      operationId: getContributionById
      parameters:
      - name: contributionId
        in: path
        description: ID of Contribution to return
        required: true
        schema:
          type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contribution'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404Contribution'
  /users/{userId}:
    get:
      tags:
      - users
      summary: Finds a User by its ID
      operationId: getUserbyId
      parameters:
      - name: userId
        in: path
        description: ID of User to return
        required: true
        schema:
          type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404User'
    put:
      tags:
      - users
      summary: Update a User of the HackerNews
      operationId: updateUser
      parameters:
      - name: userId
        in: path
        description: ID of User to update
        required: true
        schema:
          type: integer
      requestBody:
        description: Provide the about of the User
        content:
          application/json:
            schema:
              required:
              - about
              type: object
              properties:
                about:
                  type: string
                  nullable: true
                  example: 'User about'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        401:
            description: 'Error: Unauthorized'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorMissingAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedMissingAuthentication'
                  errorIncorrectAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedIncorrectAuthentication'
        403:
            description: 'Error: Forbidden'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorPrivilegeNotGrantedExample:
                    $ref: '#/components/examples/error403Forbidden'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404User'
  /comments:
    get:
        tags:
        - comments
        summary: Retrieves all the Comments created by one user (ordered by creation) or voted by one user
        operationId: getComments
        parameters:
        - name: user_id
          in: query
          description: Comment user to filter
          schema:
            type: integer
        - name: upvotedC
          in: query
          description: User to look for upvoted comments
          schema:
            type: integer
        responses:
          200:
            description: successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Comment'
          404:
            description: 'Error: Not Found'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorUserExample:
                    $ref: '#/components/examples/error404User'
          401:
            description: 'Error: Unauthorized'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorMissingAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedMissingAuthentication'
                  errorIncorrectAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedIncorrectAuthentication'
          403:
            description: 'Error: Forbidden'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorPrivilegeNotGrantedExample:
                    $ref: '#/components/examples/error403Forbidden'
    post:
      tags:
      - comments
      summary: Adds a new Comment to the HackerNews
      operationId: addComment
      requestBody:
        description: Provide the content of the new Comment and the id of the Contribution
        content:
          application/json:
            schema:
              required:
              - content
              - contr_id
              type: object
              properties:
                content:
                  type: string
                  minLength: 1
                  example: 'Comment content'
                contr_id:
                  type: integer
                  example: 1
        required: true
      responses:
        201:
          description: Comment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        400:
          description: 'Error: Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorContentEmptyExample:
                  $ref: '#/components/examples/error400ContentComment'
                errorContributionIdEmptyExample:
                  $ref: '#/components/examples/error400ContributionComment'
        401:
            description: 'Error: Unauthorized'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorMissingAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedMissingAuthentication'
                  errorIncorrectAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedIncorrectAuthentication'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404Contribution'
  /replies:
    post:
      tags:
      - replies
      summary: Adds a new Reply to the HackerNews
      operationId: addReply
      parameters:
      - name: r
        in: query
        description: indicates if the parent of the Reply is a Reply
        schema:
          type: integer
          enum: [1]
      requestBody:
        description: Provide the content of the new Reply and the id of the parent Comment/Reply
        content:
          application/json:
            schema:
              required:
              - content
              - commentreply_id
              type: object
              properties:
                content:
                  type: string
                  minLength: 1
                  example: 'Reply content'
                commentreply_id:
                  type: integer
                  example: "1"
        required: true
      responses:
        201:
          description: Reply created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reply'
        400:
          description: 'Error: Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorContentEmptyExample:
                  $ref: '#/components/examples/error400ContentReply'
                errorContributionIdEmptyExample:
                  $ref: '#/components/examples/error400CRReply'
        401:
            description: 'Error: Unauthorized'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorMissingAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedMissingAuthentication'
                  errorIncorrectAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedIncorrectAuthentication'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404CommentReply'           
  /votes:
    post:
      tags:
      - votes
      summary: Adds a Vote to a Contribution, a Comment or a Reply
      operationId: vote
      requestBody:
        description: Provide the id of the object that is being voted and its type (Contribution, Comment or Reply)
        content:
          application/json:
            schema:
              required:
              - votable_id
              - votable_type
              type: object
              properties:
                votable_id:
                  type: integer
                  example: 17
                votable_type:
                  type: string
                  enum: [contribution, comment, reply]
                  example: 'contribution'
        required: true
      responses:
        201:
          description: Vote created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vote'
        400:
          description: 'Error: Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorVotableEmptyExample:
                  $ref: '#/components/examples/error400EmptyVotableVote'
                errorTypeEmptyExample:
                  $ref: '#/components/examples/error400EmptyTypeVote'
                errorTypeIncorrectExample:
                  $ref: '#/components/examples/error400IncorrectTypeVote'
        401:
            description: 'Error: Unauthorized'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorMissingAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedMissingAuthentication'
                  errorIncorrectAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedIncorrectAuthentication'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404ContributionCommentReply' 
        409:
            description: 'Error: Conflict'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorVoteAlreadyDoneExample:
                    $ref: '#/components/examples/error409Vote'
  /votes/{voteId}:
    delete:
      tags:
      - votes
      summary: Deletes a Vote
      operationId: deleteVote
      parameters:
        - name: voteId
          in: path
          description: id of the Vote to delete
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Tweet deleted
          content:
            application/json: {}
        401:
            description: 'Error: Unauthorized'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorMissingAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedMissingAuthentication'
                  errorIncorrectAuthenticationExample:
                    $ref: '#/components/examples/error401UnauthorizedIncorrectAuthentication'
        403:
            description: 'Error: Forbidden'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorPrivilegeNotGrantedExample:
                    $ref: '#/components/examples/error403Forbidden'            
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404Vote'
components:
  schemas:
    Contribution:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          minLength: 1
          example: 'Contribution title'
        url:
          type: string
          format: url
          nullable: true
          example: 'https://www.contribution-url.com'
        text:
          type: string
          nullable: true
          example: ''
        created_at:
          type: string
          format: date-time
        tipus:
          type: string
          example: 'url'
        points:
          type: integer
          example: 0
        user:
          type: string
          format: email
          example: 'user@email.com'
        user_id:
          type: integer
          example: 1
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        about:
          type: string
          example: User about
        email:
          type: string
          example: example@gmail.com
        created_at:
          type: string
          format: date-time
        uid:
          type: string
          example: 115340955855334215894
    Comment:
      type: object
      properties:
        id:
          type: integer
          example: 1
        content:
          type: string
          minLength: 1
          example: 'Comment content'
        user_id:
          type: integer
          example: 2
        contr_id:
          type: integer
          example: 3
        created_at:
          type: string
          format: date-time
    Reply:
      type: object
      properties:
        id:
          type: integer
          example: 1
        content:
          type: string
          minLength: 1
          example: 'Reply content'
        user_id:
          type: integer
          example: 2
        commentreply_id:
          type: integer
          example: 3
        created_at:
          type: string
          format: date-time
        parent_type:
          type: boolean
    Vote:
      type:  object
      properties:
        id: 
          type: integer
          example: 1
        votable_id:
          type: integer
          example: 2
        votable_type:
          type: string
          example: 'contribution'
        voter_id:
          type: integer
          example: 3
        created_at:
          type: string
          format: date-time
    ErrorResult:
      type: object
      properties:
        status:
          type: integer
          enum: [400, 401, 403, 404, 409]
        error: 
          type: string
          enum: ["Bad Request", "Unauthorized", "Forbidden", "Not Found", "Conflict"]
        message: 
          type: string
  examples:
    error404User:
      value:
        status: 404
        error: "Not Found"
        message: "No User with that user_id"
    error401UnauthorizedMissingAuthentication:
      value:
        status: 401
        error: "Unauthorized"
        message: "Missing authentication"
    error401UnauthorizedIncorrectAuthentication:
      value:
        status: 401
        error: "Unauthorized"
        message: "Incorrect authentication"
    error403Forbidden:
      value:
        status: 403
        error: "Forbidden"
        message: "Privilege not granted"
    error404Contribution:
      value:
        status: 404
        error: "Not Found"
        message: "No Contribution with that contribution_id"
    error404CommentReply:
      value:
        status: 404
        error: "Not Found"
        message: "No Comment or Reply with that commentreply_id"
    error404ContributionCommentReply:
      value:
        status: 404
        error: "Not Found"
        message: "No Contribution, Comment or Reply with that votable_id"
    error409Contribution:
      value:
        status: 409
        error: "Conflict"
        message: "URL already exists"
    error400TitleContribution:
      value:
        status: 400
        error: "Bad Request"
        message: "Title cannot be empty"
    error400URLContribution:
      value:
        status: 400
        error: "Bad Request"
        message: "URL must be valid"
    error400ContentComment:
      value:
        status: 400
        error: "Bad Request"
        message: "Content cannot be empty"
    error400ContributionComment:
      value:
        status: 400
        error: "Bad Request"
        message: "Contr_id cannot be empty"
    error400ContentReply:
      value:
        status: 400
        error: "Bad Request"
        message: "Content cannot be empty"
    error400CRReply:
      value:
        status: 400
        error: "Bad Request"
        message: "Commentreply_id cannot be empty"
    error400EmptyVotableVote:
      value:
        status: 400
        error: "Bad Request"
        message: "Votable_id cannot be empty"
    error400EmptyTypeVote:
      value:
        status: 400
        error: "Bad Request"
        message: "Votable_type cannot be empty"
    error400IncorrectTypeVote:
      value:
        status: 400
        error: "Bad Request"
        message: "Votable_type must be contribution, comment or reply"
    error409Vote:
      value:
        status: 409
        error: "Conflict"
        message: "Trying to vote a Contribution, Comment or Reply twice"
    error404Vote:
      value:
        status: 404
        error: "Not Found"
        message: "No Vote with that vote_id"
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-KEY #Custom headers in rails apps must have the X- prefix
      in: header
security:
  - ApiKeyAuth: []